
	Ext.define('oss.view.OSSSourceDetail',{
		extend:'Ext.view.View',
		alias:'widget.sourcedetail',
		data:[{key:'initializedKey',isnull:true}],
		id:'source_detail_view',
		tpl:['<div class="sub-search" >',
		     	'<label>搜索条件</label>',
		     	'<input type="text" >',
		     '</div>',
		     '<tpl for=".">',
			     '<tpl if="!isnull" >',
				     '<div class="object-detail" >',
				     	'<div class="sub-info" >',
				     		'<i class="file-thumb tb-{suffix}" ></i>',
				     		'<div class="file-name" title="{key}" >{key}</div>',
				     		'<ul>',
				     			'<li><em>文件大小:</em></li>',
				     			'<li><em>创建时间:</em></li>',
				     			'<li><em>创建时间:</em></li>',
				     		'</ul>',
				     	'</div>',
				     	'<div class="sub-remark" ></div>',
				     '</div>',
			     '</tpl>',
		     '</tpl>',
		     '<div></div>',
		     '<div></div>'],
		store:'SourceDetail'
	});